// <auto-generated />
namespace ArticleViewerWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Again : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Again));
        
        string IMigrationMetadata.Id
        {
            get { return "202009282214006_Again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
